WebApp/Controllers/ClientsController.cs
using Business.Interfaces;
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace WebApp.Controllers;

public class ClientsController : Controller
{
    private readonly IClientService _clientService;

    public ClientsController(IClientService clientService) => _clientService = clientService;

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var clients = await _clientService.GetAllClientsAsync();
        return View("~/Views/Admin/clients.cshtml", clients);
    }


    [HttpPost]
    public async Task<IActionResult> Add(AddClientForm form)
    {

        if (!ModelState.IsValid)
        {
            var errors = ModelState
                .Where(x => x.Value?.Errors.Count > 0)
                .ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value?.Errors.Select(x => x.ErrorMessage).ToArray()
                );

            return BadRequest(new { errors });
        }

        var result = await _clientService.CreateClientAsync(form);
        if (result == 200)
            return Ok();

        return StatusCode(result);
    }
}

WebApp/Controllers/ProjectsController.cs
using Business.Dtos;
using Business.Interfaces;
using Business.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace WebApp.Controllers;

public class ProjectsController : Controller
{
    private readonly IProjectService _projectService;

    public ProjectsController(IProjectService projectService)
    {
        _projectService = projectService;

    }

    [HttpGet]
    public async Task<IActionResult> Index(bool? status)
    {
        var projects = await _projectService.GetProjectsAsync();

        if (status.HasValue)
        {
            projects = projects.Where(p => p.Status == status.Value).ToList();
        }
        return View("~/Views/Admin/Projects.cshtml", projects);
    }

    [HttpGet("details/{id}")]
    public async Task<IActionResult> GetProject(int id)
    {
        var project = await _projectService.GetProjectAsync(id);
        return project != null ? Ok(project) : NotFound();
    }



    [HttpPost]
    public async Task<IActionResult> Add(AddProjectForm form)
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelState
                .Where(x => x.Value?.Errors.Count > 0)
                .ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value?.Errors.Select(x => x.ErrorMessage).ToArray()
                );

            return BadRequest(new { errors });
        }
        var result = await _projectService.CreateProjectAsync(form);
        if (result == 200)
            return Ok();

        return StatusCode(result);
    }

    [HttpPost("admin/projects/{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] ProjectUpdateDto dto)
    {

        if (!ModelState.IsValid)
        {
            var errors = ModelState
                .Where(x => x.Value?.Errors.Count > 0)
                .ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value?.Errors.Select(x => x.ErrorMessage).ToArray()
                );

            return Json(new { success = false, errors });

        }

        var result = await _projectService.UpdateProjectAsync(dto, id);

        if (result)
            return Json(new { success = true });

        return Json(new { success = false });


    }

    [HttpDelete("admin/projects/{id}")]
    public async Task<IActionResult> DeleteProject(int id)
    {
        var project = await _projectService.GetProjectAsync(id);

        if (project == null)
            return NotFound();

        var deleted = await _projectService.DeleteProjectAsync(project);
        return deleted ? Ok() : BadRequest();
    }
}

WebApp/Views/Shared/Partials/Modals/_AddClientModal.cshtml
@model AddClientForm

<div id="addClientModal" class="modal">
    <div class="modal-content">
        <header class="modal-header">
            <h3>Add Client</h3>
            <button data-close="true" data-target="#addClientModal" type="button" class="btn-close"></button>
        </header>
        <div class="modal-body">
            <form novalidate method="post" asp-action="Add" asp-controller="Clients">

                <div class="upload-container">
                    <img src="~/images/Upload-avatar.svg" class="upload-icon" />
                </div>

                <div class="form-group">
                    <label asp-for="FirstName"></label>
                    <div class="field-group">
                        <input asp-for="FirstName" required />
                        <span asp-validation-for="FirstName"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="LastName"></label>
                    <div class="field-group">
                        <input asp-for="LastName" />
                        <span asp-validation-for="LastName"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <div class="field-group">
                        <input asp-for="Email" />
                        <span asp-validation-for="Email"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Phone"></label>
                    <div class="field-group">
                        <input asp-for="Phone" />
                        <span asp-validation-for="Phone"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Address"></label>
                    <div class="field-group">
                        <input asp-for="Address" />
                        <span asp-validation-for="Address"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="DateOfBirth"></label>
                    <div class="field-group">
                        <input asp-for="DateOfBirth" type="date" />
                        <span asp-validation-for="DateOfBirth"></span>
                    </div>
                </div>

                <button type="submit" class="btn btn-blue btn-submit">Create</button>

            </form>
        </div>

    </div>
</div>

WebApp/Views/Shared/Partials/Modals/_AddProjectModal.cshtml
@model Business.Models.AddProjectForm

<div id="addProjectModal" class="modal">
    <div class="modal-content">
        <header class="modal-header">
            <h3>Add Project</h3>
            <button data-close="true" data-target="#addProjectModal" type="button" class="btn-close"></button>
        </header>
        <div class="modal-body">
            <form novalidate method="post" asp-action="Add" asp-controller="Projects">


                <div class="upload-container">
                    <img src="~/images/Upload-image.svg" class="upload-icon" />
                </div>

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <div class="field-group">
                        <input asp-for="Name" />
                        <span asp-validation-for="Name"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="ClientName"></label>
                    <div class="field-group">
                        <input asp-for="ClientName" />
                        <span asp-validation-for="ClientName"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <div class="field-group">
                        <textarea asp-for="Description"></textarea>
                        <span asp-validation-for="Description"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="StartDate"></label>
                    <div class="field-group">
                        <input asp-for="StartDate" />
                        <span asp-validation-for="StartDate"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="EndDate"></label>
                    <div class="field-group">
                        <input asp-for="EndDate" />
                        <span asp-validation-for="EndDate"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Budget"></label>
                    <div class="field-group input-icon">                        
                        <input asp-for="Budget" type="number" step="0.01" />
                        <span asp-validation-for="Budget"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Status">Project Status</label>
                    <div class="field-group ">
                        <select asp-for="Status" class="form-control">
                            <option value="false">Ongoing</option>
                            <option value="true">Completed</option>

                        </select>
                        <span asp-validation-for="Status"></span>
                    </div>
                </div>

                <button type="submit" class="btn btn-blue btn-submit">Create</button>

            </form>
        </div>

    </div>
</div>

WebApp/Views/Shared/Partials/Modals/_AddStatusModal.cshtml
@model AddStatusForm

<div id="addStatusModal" class="modal">
    <div class="modal-content">
        <header class="modal-header">
            <h3>New Status</h3>
            <button data-close="true" data-target="#addStatusModal" type="button" class="btn-close"></button>
        </header>
        <div class="modal-body">
            <form novalidate method="post" asp-action="Add" asp-controller="Statuses">

                <div class="form-group">
                    <label asp-for="StatusName"></label>
                    <div class="field-group">
                        <input asp-for="StatusName" />
                        <span asp-validation-for="StatusName"></span>
                    </div>
                </div>              

                <button type="submit" class="btn btn-blue btn-submit">Add New Status</button>

            </form>
        </div>

    </div>
</div>

WebApp/Views/Shared/Partials/Modals/_UpdateProjectModal.cshtml
@model Business.Models.UpdateProjectForm

<div id="updateProjectModal" class="modal">
    <div class="modal-content">
        <header class="modal-header">
            <h3>Edit Project</h3>
            <button data-close="true" data-target="#updateProjectModal" type="button" class="btn-close"></button>
        </header>
        <div class="modal-body">
            <form id="updateProjectForm" novalidate method="post" asp-action="Edit" asp-controller="Projects">
                <input asp-for="Id" type="hidden" />
               

                <div class="upload-container">
                    <img src="~/images/Edit image.svg" class="upload-icon" />
                </div>
               

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <div class="field-group">
                        <input asp-for="Name" />
                        <span asp-validation-for="Name"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="ClientName"></label>
                    <div class="field-group">
                        <input asp-for="ClientName" />
                        <span asp-validation-for="ClientName"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <div class="field-group">
                        <textarea asp-for="Description"></textarea>
                        <span asp-validation-for="Description"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="StartDate"></label>
                    <div class="field-group start-end-date">
                        <input asp-for="StartDate" />
                        <span asp-validation-for="StartDate"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="EndDate"></label>
                    <div class="field-group start-end-date">
                        <input asp-for="EndDate" />
                        <span asp-validation-for="EndDate"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Budget"></label>
                    <div class="field-group input-icon">
                        <i class="fa fa-dollar"></i>
                        <input asp-for="Budget" type="number" step="0.01" />
                        <span asp-validation-for="Budget"></span>
                    </div>
                </div>

               <div class="form-group">
                    <label asp-for="Status">Project Status</label>
                    <div class="field-group ">
                        <select asp-for="Status" class="form-control">
                            <option value="false">On</option>
                            <option value="true">Completed</option>
                      
                        </select>
                        <span asp-validation-for="Status"></span>
                    </div>
                </div>


               

                <button type="submit" class="btn btn-blue btn-submit">Save</button>

            </form>
        </div>

    </div>
</div>